IF ((treePercentageGreaterThan(50) AND hasWater()) AND (NOT hasVehicle())) THEN setEcology('forest')
IF ((treePercentageGreaterThan(40) AND (NOT hasWater())) AND (NOT hasVehicle())) THEN setEcology('tundra')
IF (treePercentageLessThan(40) AND (NOT hasVehicle())) THEN setEcology('plains')
IF ((treePercentageLessThan(15) AND (NOT hasWater())) AND (NOT hasVehicle())) THEN setEcology('desert')
IF (numberOfBuildingsGreaterThan(2) AND hasVehicle()) THEN setEcology('urban')
IF (hasRiver() OR hasLake()) THEN thereIsWater()
IF maximumHeightGreaterThan(10) THEN setLandscape('high')
IF ((maximumHeightDifferenceIsLessThan(2) AND maximumHeightGreaterThan(4)) AND maximumHeightLessThan(11))  THEN setLandscape('mid')
IF maximumHeightLessThan(5) THEN setLandscape('low')
IF (ecologyIs('forest') AND hasMudpit()) THEN setClimate('tropical')
IF (ecologyIs('forest') AND (NOT hasMudpit())) THEN setClimate('moderate')
IF (ecologyIs('desert') OR ecologyIs('plains')) THEN setClimate('dry')
IF (ecologyIs('urban') AND (NOT hasWater()) THEN setClimate('dry')
IF (ecologyIs('urban') AND (hasWater() OR treePercentageGreaterThan(30)) THEN climsetClimateateIs('moderate')
IF ecologyIs('tundra') THEN setClimate('continental')
IF (ecologyIs('plains') AND (NOT hasWater())) THEN setClimate('polar')
IF (ecologyIs('tundra') AND rockPercentageGreaterThan(20)) THEN setClimate('polar')
IF ((ecologyIs('desert') OR ecologyIs('forest')) OR (ecologyIs('tundra') AND climateIs('continental'))) THEN thereAreDangerousAnimals()
IF (dangerousAnimalsArePresent() AND ( ecologyIs('desert') OR (ecologyIs('forest') AND climateIs('tropical')))) THEN thereArePoisonousAnimals()
IF (climateIs('tropical') OR climateIs('moderate')) THEN expectRain()
IF (climateIs('dry') OR climateIs('polar')) THEN setForagableFoodLevelTo(1)
IF climateIs('continental') THEN setForagableFoodLevelTo(3)
IF climateIs('moderate') THEN setForagableFoodLevelTo(5)
IF climateIs('tropical') THEN setForagableFoodLevelTo(7)
IF dangerousAnimalsArePresent() THEN addGear('defensiveWeapon')
IF thoseAnimalsArePoisonous() THEN addGear('antiVenom')
IF foragableFoodIsLessThan(4) THEN addGear('extraFood')
IF (((climateIs('dry') OR (landscapeIs('high') AND ecologyIs('plains'))) OR climateIs('polar')) OR ecologyIs('tundra')) THEN addGear('extraWater')
IF rainIsExpected() THEN addGear('poncho')
IF landscapeIs('high') THEN addGear('climbingHarness')
IF (landscapeIs('high') AND climateIs('polar')) THEN addGear('icepick') addGear('avalancheLocator')
IF (landscapeIs('mid') AND climateIs('polar')) THEN addGear('trekPoles')
IF (landscapeIs('low') AND climateIs('polar')) THEN addGear('snowShoes')
IF ((rainIsExpected() OR hasRiver()) OR (landscapeIs('low') AND climateIs('tropical')))) THEN addGear('waterproofBag')
IF (landscapeIs('high') OR hasRiver()) THEN addGear('rope')
IF climateIs('polar') THEN addGear('heavyJacket')
IF maximumHeightGreaterThan(20) THEN addGear('airTank')
IF hasLake() THEN addGear('fishingGear')